Fix

diff --git a/.github/workflows/build-rpi3-raylib-static.yaml b/.github/workflows/build-rpi3-raylib-static.yaml
--- a/.github/workflows/build-rpi3-raylib-static.yaml
+++ b/.github/workflows/build-rpi3-raylib-static.yaml
@@ -57,6 +57,7 @@ jobs:
     #  run: |
     #    find . -iname drm.h
     #    ls ./sysroot/usr/include/libdrm/drm.h
+
     - name: Verify glibc versions
       run: |
         echo "Checking glibc version in sysroot..."
@@ -64,8 +65,14 @@ jobs:
         echo "Sysroot glibc version: $SYSROOT_GLIBC_VERSION"
 
         echo "Checking glibc version used by cross-compiler..."
-        CROSS_GLIBC_VERSION=$(arm-linux-gnueabihf-gcc -print-libgcc-file-name | xargs strings | grep -oP 'GLIBC_[0-9]+\.[0-9]+' | sort -V | tail -n 1)
-        echo "Cross-compiler glibc version: $CROSS_GLIBC_VERSION"
+        LIBGCC_PATH=$(arm-linux-gnueabihf-gcc -print-libgcc-file-name)
+        if [ -f "$LIBGCC_PATH" ]; then
+          CROSS_GLIBC_VERSION=$(objdump -T "$LIBGCC_PATH" | grep -oP 'GLIBC_[0-9]+\.[0-9]+' | sort -V | tail -n 1)
+          echo "Cross-compiler glibc version: $CROSS_GLIBC_VERSION"
+        else
+          echo "Error: libgcc file not found at $LIBGCC_PATH"
+          exit 1
+        fi
 
         if [ "$SYSROOT_GLIBC_VERSION" != "$CROSS_GLIBC_VERSION" ]; then
           echo "Error: glibc versions do not match!"
